/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frame;

import client.Client;
import domain.Transaction;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author moore
 */
public class TransactionsFrame extends javax.swing.JInternalFrame {

    private static Client client;
    /**
     * Creates new form TransactionFrame
     */
    public TransactionsFrame(Client client) {
        TransactionsFrame.client = client;
        initComponents();
        addTransactionsToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Transactions");
        setToolTipText("Displays Transactions");
        setAutoscrolls(true);
//        setVisible(true);

        transactionTable.setAutoCreateRowSorter(true);
        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Transaction Date", "Transaction Time", "Equipment Id", "Event", "Customer ID", "Employee ID", "Total Amount", "Rental Request ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transactionTable.setToolTipText("Transactions Table");
        transactionTable.setName("transactionsTable"); // NOI18N
        transactionTable.setShowHorizontalLines(true);
        transactionTable.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(transactionTable);

        deleteButton.setText("Delete Transaction");
        deleteButton.setAutoscrolls(true);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int row = transactionTable.getSelectedRow();

        int result = JOptionPane.showConfirmDialog(TransactionsFrame.this, "Delete Transaction: " + (String) model.getValueAt(row,0));
        switch (result) {
            case JOptionPane.YES_OPTION:

        client.sendAction("Delete Transaction");
        client.sendObject((String) model.getValueAt(row,0));
        client.receiveResponse();

        if (client.responseFlag == true){
            JOptionPane.showMessageDialog(TransactionsFrame.this,"Transaction deleted succesfully.", "Update Equipment", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(TransactionsFrame.this,"Failed to delete Transaction.", "Delete Equipment", JOptionPane.ERROR_MESSAGE);
        }

        model.setRowCount(0);
        addTransactionsToTable();

            case JOptionPane.NO_OPTION:
            default:
        }

    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addTransactionsToTable(){
        client.sendAction("Get Transaction List");
        client.receiveResponse();
        this.tList = client.getTransactionList();

        model = (DefaultTableModel) transactionTable.getModel();
        Object rowData [] = new Object[9];
        for(int i=0; i < tList.size(); i++){
            rowData[0] = tList.get(i).getTransactionId();
            rowData[1] = tList.get(i).getTransactionDate();
            rowData[2] = tList.get(i).getTransactionTime();
            rowData[3] = tList.get(i).getequipmentId();
            rowData[4] = tList.get(i).getEvent();
            rowData[5] = tList.get(i).getCustomerId();
            rowData[6] = tList.get(i).getEmployeeId();
            rowData[7] = tList.get(i).getTotalAmount();
            rowData[8] = tList.get(i).getRentalRequestId();

            model.addRow(rowData);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables

    private ArrayList<Transaction> tList= new ArrayList<>();
    private DefaultTableModel model;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable transactionTable;
    // End of variables declaration//GEN-END:variables
}
