/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import client.Client;
import domain.Equipment;
import domain.Transaction;

import javax.swing.*;
import java.awt.print.PrinterException;

/**
 *
 * @author moore
 */
public class Invoice extends javax.swing.JInternalFrame {

    private Transaction transaction;
    private static Client client;

    /**
     * Creates new form Invoice
     */
    public Invoice(Client client, Transaction transaction) {
        Invoice.client = client;
        this.transaction = transaction;
        initComponents();
        populateTextpane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        invoicePane = new javax.swing.JTextPane();
        printButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Invoice");
        setAutoscrolls(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
//        setVisible(true);
        invoicePane.setContentType("text/plain");
        jScrollPane1.setViewportView(invoicePane);

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printButton)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try{
            invoicePane.print();
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(Invoice.this,"Unable to print invoice", "Print Invoice", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_printButtonActionPerformed


    private void populateTextpane(){

        client.sendAction("Get Equipment");
        client.sendObject(transaction.getequipmentId());
        client.receiveResponse();
        Equipment eq = client.getEquipment();
        String invoiceInfo;

        invoiceInfo = "\n\nGrizzly's Entertainment Equipment Rental\n\n ";
        invoiceInfo += "--------------------------------------------";
        invoiceInfo +=  "\n\nTransaction Date: " + transaction.getTransactionDate() +
                        "\nTransaction Time: " + transaction.getTransactionTime() +
                        "\nCustomer ID: " + transaction.getCustomerId() +
                        "\nEmployee ID: " + transaction.getEmployeeId();
        invoiceInfo += "\n\n--------------------------------------------";
        invoiceInfo += "\n\nEquipment ID: " + transaction.getequipmentId();
        invoiceInfo += "\nEquipment Type: " + eq.getEquipmentType();
        invoiceInfo += "\nEquipment Name: " + eq.getEquipmentName();
        invoiceInfo += "\nCost Per Day: " + eq.getEquipmentName();
        invoiceInfo += "\nTotal : " + transaction.getTotalAmount();

        invoicePane.setText(invoiceInfo);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane invoicePane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printButton;
    // End of variables declaration//GEN-END:variables
}
