/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import client.Client;
import domain.Transaction;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author moore
 */
public class TransactionsFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form TransactionFrame
     */
    public TransactionsFrame(Client client) {
        TransactionsFrame.client = client;
        initComponents();
        addTransactionsToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        invoiceButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Transactions");
        setToolTipText("Displays Transactions");
        setAutoscrolls(true);
//        setVisible(true);

        transactionTable.setAutoCreateRowSorter(true);
        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Transaction Date", "Transaction Time", "Equipment Id", "Event", "Customer ID", "Employee ID", "Total Amount", "Rental Request ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transactionTable.setToolTipText("Transactions Table");
        transactionTable.setName("transactionsTable"); // NOI18N
        transactionTable.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(transactionTable);

        invoiceButton.setText("View Invoice");
        invoiceButton.setAutoscrolls(true);
        invoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(invoiceButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(invoiceButton)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceButtonActionPerformed

        int row = transactionTable.getSelectedRow();
        Transaction transaction = new Transaction();


        transaction.setTransactionId((String) model.getValueAt(row,0));
        transaction.setTransactionDate((String) model.getValueAt(row,1));
        transaction.setTransactionTime((String) model.getValueAt(row,2));
        transaction.setequipmentId((String) model.getValueAt(row,3));
        transaction.setEvent((String) model.getValueAt(row,4));
        transaction.setCustomerId((String) model.getValueAt(row,5));
        transaction.setEmployeeId((String) model.getValueAt(row,6));
        transaction.setTotalAmount((Float) model.getValueAt(row,7));
        transaction.setRentalRequestId((String) model.getValueAt(row,8));

        App.desktopPane.add(new Invoice(client,transaction)).setVisible(true);
    }//GEN-LAST:event_invoiceButtonActionPerformed


    private void addTransactionsToTable(){
        client.sendAction("Get Customer Transaction List");
        client.sendObject(client.getLoggedInCustomer().getCustomerId());
        client.receiveResponse();
        ArrayList<Transaction> tList;
        tList = client.getTransactionList();

        model = (DefaultTableModel) transactionTable.getModel();
        Object rowData [] = new Object[9];
        for(int i=0; i < tList.size(); i++){
            rowData[0] = tList.get(i).getTransactionId();
            rowData[1] = tList.get(i).getTransactionDate();
            rowData[2] = tList.get(i).getTransactionTime();
            rowData[3] = tList.get(i).getequipmentId();
            rowData[4] = tList.get(i).getEvent();
            rowData[5] = tList.get(i).getCustomerId();
            rowData[6] = tList.get(i).getEmployeeId();
            rowData[7] = tList.get(i).getTotalAmount();
            rowData[8] = tList.get(i).getRentalRequestId();

            model.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton invoiceButton;

    private DefaultTableModel model;
    private static Client client;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable transactionTable;
    // End of variables declaration//GEN-END:variables
}
